### ISSUE TITLE
Very interested in this project!

### ISSUE THREAD

**Issue by hobbzey** [dounix/neopi#1]
Hey I know this probably isn't the place for this, but I just wanted to express my great interest in this project. And I have to ask, are you going to be posting the code? Even if it was just a fast SD card image dump, as a fellow Tajima owner, I would LOVE to see how you pulled this off!

**Comment by dounix** [comment]
Sure, it works, but It's a mess in a local repo :) , but I'll put something up here.
Really just some fluff around pushing designs over the serial port.  the protocol is just a dst file w/ a header stripped off if I recall.
